/var/spool/slurm/slurmd/state/job18382825/slurm_script: line 11: SBATCH: command not found
/var/spool/slurm/slurmd/state/job18382825/slurm_script: line 12: SBATCH: command not found
/var/spool/slurm/slurmd/state/job18382825/slurm_script: line 13: SBATCH: command not found
/var/spool/slurm/slurmd/state/job18382825/slurm_script: line 14: SBATCH: command not found
/var/spool/slurm/slurmd/state/job18382825/slurm_script: line 15: SBATCH: command not found
/var/spool/slurm/slurmd/state/job18382825/slurm_script: line 26: CL_Zofia_One_Class_test_file.py: command not found
Input Notebook:  ./time_dependency/optimal_t_vs_n.ipynb
Output Notebook: ./time_dependency/optimal_t_vs_n.ipynb
Traceback (most recent call last):
  File "/cluster/home/zbinczyk/python/lib/python3.12/site-packages/papermill/iorw.py", line 199, in read
    json.loads(path)
  File "/cluster/home/zbinczyk/python/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/zbinczyk/python/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/zbinczyk/python/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/home/zbinczyk/python/bin/papermill", line 8, in <module>
    sys.exit(papermill())
             ^^^^^^^^^^^
  File "/cluster/home/zbinczyk/python/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/zbinczyk/python/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/cluster/home/zbinczyk/python/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/zbinczyk/python/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/zbinczyk/python/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/zbinczyk/python/lib/python3.12/site-packages/papermill/cli.py", line 235, in papermill
    execute_notebook(
  File "/cluster/home/zbinczyk/python/lib/python3.12/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/zbinczyk/python/lib/python3.12/site-packages/papermill/iorw.py", line 499, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/zbinczyk/python/lib/python3.12/site-packages/papermill/iorw.py", line 96, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/zbinczyk/python/lib/python3.12/site-packages/papermill/iorw.py", line 203, in read
    raise e
  File "/cluster/home/zbinczyk/python/lib/python3.12/site-packages/papermill/iorw.py", line 193, in read
    with open(path, encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './time_dependency/optimal_t_vs_n.ipynb'
